---
- name: Install nginx with VH
  hosts: webservers
  become: true
  become_method: sudo
  gather_facts: no

  vars:
    sites:
    - "etis.com"
    - "fizmat.com"
    - "biohim.ru"

  roles:
  - nginx-vhosts
